# samsung2_original.parquet 생성

`data/samsung2.parquet` 는 IMU 축이 samsung1 기준(YXZ)으로 재라벨링된 정렬본이다.
여기서 **`triceps_X` ↔ `triceps_Y` 축 값을 맞바꿔** 재라벨링 *안 된* 원본을
`data/samsung2_original.parquet` 로 저장한다.

- 컬럼명(`triceps_X`, `triceps_Y`, `triceps_Z`)은 그대로 두고 **값만 스왑**한다.
  (전처리 코드가 컬럼명으로 feature 를 선택하기 때문)
- 나머지 컬럼은 손대지 않는다.

In [1]:
import pandas as pd

SRC = '../data/samsung2.parquet'
DST = '../data/samsung2_original.parquet'

df = pd.read_parquet(SRC)
print('shape:', df.shape)
print('columns:', list(df.columns))
df[['triceps_X', 'triceps_Y', 'triceps_Z']].head()

shape: (26224560, 12)
columns: ['TimeStamp', 'Index_Time', 'Save_Time', 'beep', 'csv_filename_l', 'subject_id', 'exercise', 'biceps', 'triceps', 'triceps_Y', 'triceps_X', 'triceps_Z']

    triceps_X   triceps_Y   triceps_Z
0  443.835999  754.692017  273.279999
1  443.835999  754.692017  273.279999
2  443.835999  754.692017  273.279999
3  443.835999  754.692017  273.279999
4  443.835999  754.692017  273.279999

In [2]:
# triceps_X <-> triceps_Y 값 스왑 (컬럼명은 유지)
df['triceps_X'], df['triceps_Y'] = df['triceps_Y'].copy(), df['triceps_X'].copy()
df[['triceps_X', 'triceps_Y', 'triceps_Z']].head()

    triceps_X   triceps_Y   triceps_Z
0  754.692017  443.835999  273.279999
1  754.692017  443.835999  273.279999
2  754.692017  443.835999  273.279999
3  754.692017  443.835999  273.279999
4  754.692017  443.835999  273.279999

In [3]:
# 검증: 스왑된 X 가 원본 Y 와, 스왑된 Y 가 원본 X 와 일치하는지 확인
orig = pd.read_parquet(SRC)
assert df['triceps_X'].equals(orig['triceps_Y'])
assert df['triceps_Y'].equals(orig['triceps_X'])
assert df['triceps_Z'].equals(orig['triceps_Z'])
print('swap OK')

swap OK

In [4]:
df.to_parquet(DST, index=False)
print('saved ->', DST)
print('shape:', df.shape)

saved -> ../data/samsung2_original.parquet
shape: (26224560, 12)